config/routes.rb
Rails.application.routes.draw do
  root 'top_page#index'
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }, skip: :sessions
  devise_scope :user do
    delete 'users/logout', to: 'users/sessions#destroy'
    delete 'users/destroy', to: 'users/registrations#destroy'
    get 'users/index', to: 'users/admin#index'
    patch 'users/approve', to: 'users/admin#approve'
    patch 'users/admin', to: 'users/admin#admin'
  end

  post :scrape, to: 'scrape#scrape'
  namespace :scrape do
    get :index
    get :lineblog
    get :ameblo
    get :instagram
    get :twitter
    get :official_site
    get :news_site
    get :youtube
  end

  resources :media_contents, constraints: { id: /\d+/ }, only: [ :index, :edit, :show, :update ] do
    collection do
      get :tmp
      patch :tmp, to: 'media_contents#multiple'
      get :deletion_request
      patch :deletion_request, to: 'media_contents#hide'
      get :search
    end
  end
  get :pictures, to: 'media_contents#pictures'
  get :videos, to: 'media_contents#videos'
  
  get 'tweets' => 'tweet#index'
end

app/controllers/top_page_controller.rb
class TopPageController < ApplicationController
  skip_before_action :authenticate_user!
  def index
  end
end

app/helpers/top_page_helper.rb
module TopPageHelper
end

app/views/top_page/index.html.haml
- provide :title, 'トップページ'

-if user_signed_in?
  %h2 こんにちは、#{current_user.username}さん
  .heading
    = button_to '一覧表示', media_contents_path, method: :get, class: "btn btn-primary"
    - if current_user.approved?
      = button_to 'メディアを追加する', scrape_index_path, method: :get, class: "btn btn-default"
      - if current_user.admin?
        = button_to 'ツイートする', tweets_path, method: :get, class: "btn btn-default"
        = button_to 'ユーザ管理', users_index_path, method: :get, class: "btn btn-default"
- else
  %h2 Twitter認証してログインしてください
  .heading
    = button_to 'Twitter認証', user_twitter_omniauth_authorize_path, method: :get, class: 'btn btn-primary'