config/routes.rb
Rails.application.routes.draw do
  root 'top_page#index'
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }, skip: :sessions
  devise_scope :user do
    delete 'users/logout', to: 'users/sessions#destroy'
    delete 'users/destroy', to: 'users/registrations#destroy'
    get 'users/index', to: 'users/admin#index'
    patch 'users/approve', to: 'users/admin#approve'
    patch 'users/admin', to: 'users/admin#admin'
  end

  post :scrape, to: 'scrape#scrape'
  namespace :scrape do
    get :index
    get :lineblog
    get :ameblo
    get :instagram
    get :twitter
    get :official_site
    get :news_site
    get :youtube
  end

  resources :media_contents, constraints: { id: /\d+/ }, only: [ :index, :edit, :show, :update ] do
    collection do
      get :tmp
      patch :tmp, to: 'media_contents#multiple'
      get :deletion_request
      patch :deletion_request, to: 'media_contents#hide'
      get :search
    end
  end
  get :pictures, to: 'media_contents#pictures'
  get :videos, to: 'media_contents#videos'
  
  get 'tweets' => 'tweet#index'
end

app/models/media_content.rb
class MediaContent < ApplicationRecord
  enum content_type: {
    picture: 1,
    video: 2,
  }
  validates :member_id, inclusion: { in: [1, 2, 3] }
  
  acts_as_taggable
  belongs_to :member
  belongs_to :event, optional: true
  accepts_nested_attributes_for :event, reject_if: :event_blank_or_exist?
  
  scope :paginate,   ->(page_id) { page(page_id).per(50) }
  scope :desc_order, -> { order('date DESC') }
  scope :asc_order,  -> { order('date ASC') }
  scope :allowed,    -> { where(tmp: false, removed: false) }
  scope :temporary,  -> { where(tmp: true,  removed: false) }
  scope :selected_by_date,   ->(params) { where('date >= ? AND date <= ?', params[:since], params[:until]).allowed }
  scope :selected_by_member, ->(params) { joins(:member).merge(Member.id_is params[:member]).allowed }
  scope :selected_by_event,  ->(params) { joins(:event).merge(Event.name_like params[:event]).allowed }
  scope :selected_by_tag,    ->(params) { tagged_with(params[:tag], any: true, wild: true).allowed }
  scope :selected_by_media,  ->(params) { where('address LIKE ?', "%#{params[:media]}%").allowed }
  
  # class methods
  def self.remove(ids)
    media_contents = where(id: ids)
    media_contents.update_all(removed: true)
    media_contents.each do |media_content|
      media_content.delete_from_storage
    end
  end
  
  # instance methods
  def delete_from_storage
    begin
      case content_type
      when 'picture'
        S3_BUCKET.object(s3_address).delete
      when 'video'
        S3_BUCKET.object(s3_address).delete
        S3_BUCKET.object(s3_ss_address).delete
      end
    rescue
      puts $!
      puts "#{media_content.address} is maybe not exists."
    end
  end
  
  def thumbnail
    case content_type
    when 'picture'
      attributes['address']
    when 'video'
      ss_address
    end
  end
  
  private
  
  def s3_address
    attributes['address'].gsub(ENV['S3_BUCKET_URL'], '')
  end
  
  def ss_address
    attributes['address'].gsub(%r{\.[^.]*?$}, '.jpg')
  end
  
  def s3_ss_address
    s3_address.gsub(%r{\.[^.]*?$}, '.jpg')
  end
  
  def event_blank_or_exist?(attributes)
    if attributes[:name].blank? || Event.where(name: attributes[:name]).any?
      return true
    end
    return false
  end
end

app/controllers/media_contents_controller.rb
class MediaContentsController < ApplicationController
  before_action :set_media_content, only: [:show, :edit, :update]
  before_action :approved_user!, only: [:tmp, :deletion_request, :destroy]
  before_action :admin_user!, only: [:multiple]

  def tmp
    @media_contents = MediaContent.temporary.desc_order.paginate(params[:page])
  end
  
  def multiple
    if params[:remove] && MediaContent.remove(params[:media_content_ids])
      redirect_back fallback_location: tmp_media_contents_path, notice: 'データベース及びストレージからの削除完了しました'
    elsif params[:show] && MediaContent.where(id: params[:media_content_ids]).update_all(tmp: false)
      redirect_back fallback_location: tmp_media_contents_path, notice: '一覧に表示します'
    else
      redirect_back fallback_location: tmp_media_contents_path, alert: '更新に失敗しました'
    end
  end
  
  def search
    @media_contents = MediaContent.send("selected_by_#{params[:column]}", search_params).desc_order.paginate(params[:page])
  end
  
  def deletion_request
    @media_contents = MediaContent.allowed.desc_order.paginate(params[:page])
  end
  
  def hide
    if MediaContent.where(id: params[:media_content_ids]).update_all(tmp: true)
      redirect_to media_contents_path, notice: '削除申請を受け付けました'
    else
      redirect_back fallback_location: media_contents_path, alert: '削除申請に失敗しました'
    end
  end
  
  def pictures
    @media_contents = Picture.allowed.desc_order.paginate(params[:page])
  end

  def videos
    @media_contents = Video.allowed.desc_order.paginate(params[:page])
  end

  def index
    @media_contents = MediaContent.allowed.desc_order.paginate(params[:page])
  end

  def show
  end

  def edit
  end
  
  def update
    if @media_content.update(media_content_params)
      respond_to do |format|
        flash[:notice] = '更新完了しました'
        format.js {render 'show'}
      end
    else
      respond_to do |format|
        flash[:notice] = '更新に失敗しました。'
        format.js {render 'edit'}
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_media_content
      @media_content = MediaContent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def search_params
      params.require(:media_content).permit(:since, :until, :member, :event, :tag, :media)
    end
    
    def media_content_params
      params.require(:media_content).permit(:member_id, :event_id, :tag_list, :date, :article_url, event_attributes: [:name])
    end
end

app/helpers/media_contents_helper.rb
module MediaContentsHelper
end

app/views/media_contents/_edit.html.haml
= form_for(@media_content, method: :patch, remote: true) do |f|
  .modal-body
    .center-block.member-form
      = f.collection_select :member_id, Member.all, :id, :name
    .center-block.event-form
      = f.collection_select :event_id, Event.all, :id, :name, include_blank: true
      -# this button can be pushed only at once.
      %button.btn.new-record{type: 'button'} イベント新規作成
    .center-block.date-form
      = f.date_field :date, class: 'form-control'
    .center-block.tags-form
      = f.text_field :tag_list, {value: @media_content.tag_list.join(','), 'data-role': 'tagsinput', placeholder: 'tag separeted with , or Enter', class: 'tag-list'}
    .center-block.article-form
      = f.url_field :article_url
  .modal-footer
    = f.submit class: 'btn btn-primary'
    %button.btn{type: 'button', aria: {hidden: true}, data: {dismiss: 'modal'}} Close

app/views/media_contents/_footer.html.haml
%footer
  %nav.navbar.navbar-default.navbar-fixed-bottom{:role => "navigation"}
    .container-fluid
      %ul.nav.navbar-nav
        - if action_name == 'tmp'
          %li= button_tag 'すべて選択', id: 'check_all', type: 'button', class: 'btn btn-default'
          %li= button_tag 'すべて解除', id: 'uncheck_all', type: 'button', class: 'btn btn-default'
      
      %ul.nav.navbar-nav.navbar-right
        / index
        - if action_name == 'index' && current_user.approved?
          %li= link_to '削除申請モードへ', deletion_request_media_contents_path
        / deletion_request
        - if action_name == 'deletion_request'
          %li= link_to '閲覧モードへ', media_contents_path
          %li= submit_tag '削除申請', class: "btn btn-default", method: :patch
        / tmp
        - if action_name == 'tmp'
          %li= link_to '閲覧モードへ', media_contents_path
          %li= submit_tag '削除', data: { confirm: '削除しますか？' }, class: "btn btn-default", name: "remove"
          %li= submit_tag '表示許可', class: "btn btn-default", name: "show"
        / search
        - if action_name == 'search' && current_user.approved?
          / search結果をそのまま表示して削除申請できるようにしたい（idsをそのまま渡せば良い？）
          %li= link_to '削除申請モードへ', deletion_request_media_contents_path

app/views/media_contents/_media_content.html.haml
.media_content
  - if %w(index search pictures videos).include?(action_name)
    = link_to image_tag(media_content.thumbnail, class: "my-thumbnail img-rounded modalable"), media_content_path(id: media_content.id), method: :get, remote: true
    - if media_content.content_type == 'video'
      -# videoならimages/item/playmark.pngを重ねて表示する
  
  - if %w(deletion_request tmp).include?(action_name)
    = image_tag media_content.thumbnail, class: "my-thumbnail img-rounded selectable"
    - if media_content.content_type == 'video'
      -# videoならimages/item/playmark.pngを重ねて表示する
    = check_box_tag 'media_content_ids[]', media_content.id, false, class: 'multiple_checkbox'
    = image_tag '/images/item/checkmark.png', class: "checkmark"

app/views/media_contents/_modal.html.haml
#show_modal.modal.fade{aria: {hidden: 'true', labelledby: 'modal_label'}, role: 'dialog', tabindex: '-1' }
  .modal-dialog.modal-lg
    .modal-content

app/views/media_contents/_show.html.haml
.modal-header
  %button.close{aria: {hidden: 'true'}, data: {dismiss: 'modal'}, role: 'button'} x
  %h3#modal_label 詳細
- case @media_content.content_type
- when 'picture'
  = image_tag @media_content.address, class: 'img-rounded', id: 'modal-image'
- when 'video'
  = video_tag @media_content.address, id: 'modal-video', controls: true, autoplay: true
.modal-form
  .modal-body
    .center-block
      %p メンバー：#{@media_content.member.name}
    .center-block 
      - if @media_content.event.nil?
        %p イベント：なし
      - else
        %p イベント：#{@media_content.event.name}
    .center-block
      %p 日時：#{@media_content.date}
    .center-block
      = @media_content.tag_list.join(' ')
    .center-block
      = link_to '元記事', @media_content.article_url, class: 'btn btn-default', target: '_blank'
  .modal-footer
    = link_to 'Edit', edit_media_content_path(@media_content), class: 'btn btn-primary', remote: true
    %button.btn{aria: {hidden: true}, data: {dismiss: 'modal'}} Close

app/views/media_contents/deletion_request.html.haml
- provide :title, '削除申請'

= form_tag deletion_request_media_contents_path, method: :patch do
  #masonry-container.transitions-enabled.centered.clearfix
    .sizer
    .page
      = render @media_contents
  = paginate @media_contents
  = render 'footer'

app/views/media_contents/edit.js.erb
$('.modal-form').html("<%= escape_javascript(render 'edit') %>");
$('input[data-role=tagsinput]').tagsinput();
$('.new-record').on('click', function(){
  if($(this).parent().hasClass('event-form')) {
    $(this).parent().append('<input placeholder="event title" type="text" name="media_content[event_attributes][name]" id="media_content_event_attributes_name">');
    $(this).css('display', 'none');
  }
});

app/views/media_contents/index.html.haml
- provide :title, '一覧表示'
= render 'modal'

#masonry-container.transitions-enabled.centered.clearfix
  .sizer
  .page
    = render @media_contents
= paginate @media_contents
= render 'footer'

app/views/media_contents/index.js.erb
$("#masonry-container").append("<div class='page'><%= escape_javascript(render @media_contents) %></div>");

app/views/media_contents/pictures.html.haml
- provide :title, '画像一覧表示'
= render 'modal'

#masonry-container.transitions-enabled.centered.clearfix
  .sizer
  .page
    = render partial: 'media_content', collection: @media_contents
= paginate @media_contents
= render 'footer'

app/views/media_contents/search.html.haml
- provide :title, '検索結果'
= render 'modal'

#masonry-container.transitions-enabled.centered.clearfix
  .sizer
  .page
    = render @media_contents
= paginate @media_contents
= render 'footer'

app/views/media_contents/show.js.erb
$('.modal-content').html("<%= j(render 'show') %>");
$('#show_modal').modal('show');
$('#notice').html(
  "<% if flash[:notice] %>" +
  "  <%= j(javascript_tag %Q{alert('#{flash.now[:notice]}')}) %>" +
  "<% end %>");
$('#show_modal').on('click.dismiss.bs.modal', function(){
  video = document.getElementById('modal-video');
  video.pause();
});

app/views/media_contents/tmp.html.haml
- provide :title, '表示/削除'

= form_tag tmp_media_contents_path, method: :patch do
  #masonry-container.transitions-enabled.centered.clearfix
    .sizer
    .page
      = render @media_contents
  = paginate @media_contents
  = render 'footer'

app/views/media_contents/videos.html.haml
- provide :title, '動画一覧表示'
= render 'modal'

#masonry-container.transitions-enabled.centered.clearfix
  .sizer
  .page
    = render partial: 'media_content', collection: @media_contents
= paginate @media_contents
= render 'footer'