config/routes.rb
Rails.application.routes.draw do
  root 'top_page#index'
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }, skip: :sessions
  devise_scope :user do
    delete 'users/logout', to: 'users/sessions#destroy'
    delete 'users/destroy', to: 'users/registrations#destroy'
    get 'users/index', to: 'users/admin#index'
    patch 'users/approve', to: 'users/admin#approve'
    patch 'users/admin', to: 'users/admin#admin'
  end

  post :scrape, to: 'scrape#scrape'
  namespace :scrape do
    get :index
    get :lineblog
    get :ameblo
    get :instagram
    get :twitter
    get :official_site
    get :news_site
    get :youtube
  end

  resources :media_contents, constraints: { id: /\d+/ }, only: [ :index, :edit, :show, :update ] do
    collection do
      get :tmp
      patch :tmp, to: 'media_contents#multiple'
      get :deletion_request
      patch :deletion_request, to: 'media_contents#hide'
      get :search
    end
  end
  get :pictures, to: 'media_contents#pictures'
  get :videos, to: 'media_contents#videos'
  
  get 'tweets' => 'tweet#index'
end

app/models/scrape/ameblo_crawler.rb
class Scrape::AmebloCrawler
  attr_accessor :errors
  
  def initialize(params)
    member_id = params[:member_id]
    event_id = params[:event_id]
    new_event = params[:event_attributes]
    tag_list = params[:tag_list]
    tmp = params[:tmp]
    @article_url = params[:article_url]
    @article_url.match %r{http://ameblo.jp/(.+?)/entry-\d+?\.html$} rescue nil
    @amebaID = params[:amebaID] || $1
    @host = "http://ameblo.jp/#{@amebaID}/"
    @downloader = Scrape::Downloader.new("ameblo/#{@amebaID}/", member_id, event_id, new_event, tag_list, tmp)
  end
  
  def validate
    if @amebaID.nil?
      @errors = '無効なURLです'
      return false
    elsif skip_IDs.include?(@amebaID)
      @errors = '追跡済みのユーザは指定しないでください'
      return false
    end
    true
  end
  
  def crawl(type: :recent)
    case type
    when :all
      all_entrylist.each do |entrylist_url|
        single_crawl(entrylist_url)
      end
    when :recent
      single_crawl("#{@host}entrylist.html")
    end
  end
  
  def manually_crawl
    parse_article
  end
  
  private
  
  def all_entrylist
    article_num = 0
    urls = []
    doc = Nokogiri::HTML.parse(open(@host))
    doc.xpath('//div[@class="skinMenu archiveMenu"]/div[1]/div[2]/ul/li/a').each do |archive|
      article_num = article_num + archive.text.gsub(/.*\( ([\d]*) \)/, '\1').to_i
    end
    1.upto(article_num / 20 + 1) do |i|
      urls << "#{@host}entrylist-#{i}.html"
    end
    return urls
  end
  
  def single_crawl(url)
    Dir.mkdir('tmp/anemone/') unless Dir.exist?('tmp/anemone')
    options = {
      depth_limit: 1,
      delay: 2,
      storage: Anemone::Storage.PStore("tmp/anemone/#{@amebaID}.dmp")
    }
    Anemone.crawl(url, options) do |anemone|
      anemone.focus_crawl do |page|
        page.links.keep_if do |link|
          link.to_s.match %r{http://ameblo.jp/#{@amebaID}/entry-\d+?\.html$}
        end
      end
      
      begin
        anemone.on_every_page do |page|
          puts "image on #{page.url} :"
          @article_url = page.url
          parse_article
        end
      rescue => ex
        puts ex
        puts 'please retry'
      end
    end
  end

  def parse_article
    doc = Nokogiri::HTML.parse(open(@article_url))
    doc.xpath('//div[@class="articleText" or  @class="subContentsInner"]//a/img').each do |img|
      image_url = img.attribute('src').value.gsub(/t[\d]*_/, 'o').gsub(/\?.*$/, '')
      
      datestr = image_url.gsub(/.*user_images\/(.*?)\//, '\1')
      dateary = [datestr.slice(0,4), datestr.slice(4,2), datestr.slice(6,2)]
      date = Time.local(*dateary)
      
      @downloader.save_media(:image, image_url, @article_url, date)
    end
  end
  
  def skip_IDs
    array = []
    (Settings.ameblo.regular_crawl + Settings.ameblo.stopped_updating).each do |obj|
      array << obj.ID
    end
    return array
  end
end

app/models/scrape/downloader.rb
class Scrape::Downloader
  def initialize(dir_name, member_id, event_id, new_event, tag_list, tmp)
    @dir_name = "images/#{dir_name}"
    @member_id = member_id
    @event_id = event_id
    @new_event = new_event.blank? ? {} : new_event
    @tag_list = tag_list
    @tmp = tmp
  end
  
  def save_youtube(id, uri, article_uri)
    filepath = "images/youtube/#{id}.mp4"
    fullpath = Scrape::Helper.fullpath(filepath)
    
    if Video.find_by_address(fullpath)
      puts "#{uri} has been already saved or deleted"
      return
    end
    
    unless download_youtube(filepath, fullpath, uri, id)
      puts 'download failed'
      return
    end
    
    
    datestr = Nokogiri::HTML.parse(open(uri)).xpath('//meta[@itemprop="datePublished"]').attribute('content').value
    date = Time.parse(datestr)
    
    video = Video.create(
      address: fullpath,
      article_url: article_uri.to_s,
      member_id: @member_id,
      event_id: @event_id,
      event_attributes: @new_event,
      tag_list: @tag_list,
      date: date,
      tmp: @tmp,
    )
    video.screenshot
  end
  
  def save_media(media_type, uri, article_uri, date, filepath = nil)
    # filepathを指定したい時は指定してもらう感じで。
    filepath = filepath ? "images/#{filepath}" : "#{@dir_name}#{File.basename(uri)}"
    fullpath = Scrape::Helper.fullpath(filepath)
    
    # そもそもダウンロードしないものを弾く
    if Settings.extname.images.exclude?(File.extname(filepath)) && Settings.extname.videos.exclude?(File.extname(filepath))
      puts "#{uri}'s extension is not allowed to download"
      return
    elsif media_type == :image && Picture.find_by_address(fullpath)
      puts "#{uri} has already been saved or deleted"
      return
    elsif media_type == :video && Video.find_by_address(fullpath)
      puts "#{uri} has already been saved or deleted"
      return
    end
    
    unless download_media(filepath, fullpath, uri)
      puts 'download failed'
      return
    end
    
    case media_type
    when :image
      Picture.create(
        address: fullpath,
        article_url: article_uri.to_s,
        member_id: @member_id,
        event_id: @event_id,
        event_attributes: @new_event,
        tag_list: @tag_list,
        date: date,
        tmp: @tmp,
      )
    when :video
      video = Video.create(
        address: fullpath,
        article_url: article_uri.to_s,
        member_id: @member_id,
        event_id: @event_id,
        event_attributes: @new_event,
        tag_list: @tag_list,
        date: date,
        tmp: @tmp,
      )
      video.screenshot
    end
  end
  
  private
  
  def download_youtube(filepath, fullpath, uri, id)
    tmpfile = "tmp/#{id}.mp4"
    obj = S3_BUCKET.object(filepath)
    
    if obj.exists?
      puts "#{fullpath} already exists"
      return true
    end
    
    puts "download #{uri} to #{fullpath}"
    options = {
      output: tmpfile,
      format: :best,
      no_warnings: true
    }
    YoutubeDL.download(uri.to_s, options) rescue (puts $!.to_s; return false)
    obj.put(body: File.open(tmpfile))
    File.delete(tmpfile)
  end
  
  def download_media(filepath, fullpath, uri)
    obj = S3_BUCKET.object(filepath)
    
    # 既にダウンロードしてある場合はスキップ
    if obj.exists?
      puts "#{fullpath} already exists"
      return true
    end
    
    puts "download #{uri} to #{fullpath}"
    obj.put(body: open(uri)) rescue (puts $!.to_s; return false)
  end
end

app/models/scrape/helper.rb
class Scrape::Helper
  def self.write_mode(uri)
    "w:#{open(uri).to_s.encoding.to_s}"
  end

  def self.fullpath(filepath)
    "#{ENV['S3_BUCKET_URL']}#{filepath}"
  end

  def self.url(page, src)
    if self.absolute_path?(src)
      src
    else
      base_uri = Addressable::URI.parse(page).normalize
      (base_uri + src).to_s
    end
  end

  def self.absolute_path?(str)
    Addressable::URI.parse(str).scheme != nil
  end
end

app/models/scrape/instagram_crawler.rb
class Scrape::InstagramCrawler
  include Capybara::DSL
  
  attr_accessor :errors
  
  def initialize(params)
    ::Capybara.current_driver = :poltergeist
    ::Capybara.javascript_driver = :poltergeist
    ::Capybara.default_max_wait_time = 20
    ::Capybara.app_host = 'https://www.instagram.com/?hl=eg'
    ::Capybara.register_driver :poltergeist do |app|
      ::Capybara::Poltergeist::Driver.new(app, inspector: true, js_errors: false)
    end
    @yaml_file = S3_BUCKET.object('config/instagram.yml')
    
    member_id = params[:member_id]
    event_id = params[:event_id]
    new_event = params[:event_attributes]
    tag_list = params[:tag_list]
    tmp = params[:tmp]
    @article_url = params[:article_url].try(:gsub, %r{\?.*$}, '')
    open(@article_url).read.match %r{\(@(.+?)\)} rescue nil
    @instaID = params[:instaID] || $1
    @downloader = Scrape::Downloader.new("instagram/#{@instaID}/", member_id, event_id, new_event, tag_list, tmp)
  end
  
  def validate
    if skip_IDs.include?(@instaID)
      @errors = '追跡済みのユーザは指定しないでください'
      return false
    elsif @instaID.nil? || !@article_url.match(%r{https://www.instagram.com/p/.+?/$})
      @errors = '無効なURLです'
      return false
    end
    true
  end
  
  def crawl(type: :recent)
    puts "visit user page of #{@instaID}"
    visit("#{@instaID}?hl=eg")
    case type
    when :all
      @article_urls = load_yaml
      check_recent_posts
      @article_urls.each do |article_url|
        parse_post(article_url)
      end
      save_yaml
    when :recent
      @article_urls = []
      check_recent_posts
      @article_urls.each do |article_url|
        parse_post(article_url)
      end
      save_yaml
    end
  end
  
  def manually_crawl
    parse_post(@article_url)
  end
  
  private
  
  def load_yaml
    puts "load from yaml file 'config/instagram.yml'"
    YAML.load(@yaml_file.get.body.read)
  end
  
  def save_yaml
    puts "save to yaml file 'config/instagram.yml'"
    @yaml_file.put(body: @article_urls.to_yaml) rescue puts $!
  end
  
  def check_recent_posts
    puts 'checking recent posts ...'
    click_link 'Load more'
    all(:xpath, '//a[@class="_8mlbc _vbtk2 _t5r8b"]').each do |result|
      @article_urls << result[:href].gsub(/\?.*$/, "")
    end
    @article_urls.uniq!
  end
  
  def skip_IDs
    Settings.instagram.regular_crawl.map{|obj| obj.ID}
  end
  
  def parse_post(article_url)
    doc = Nokogiri::HTML.parse(open("#{article_url}?hl=ja"))
    
    datestr = doc.at('meta[@property="og:title"]').attribute('content').value
    if datestr.include?('午前')
      date = Time.local(*datestr.scan(/\d+/))
    else
      date = Time.local(*datestr.scan(/\d+/))+(60*60*12)
    end
    
    if doc.at('//meta[@content="video"]')
      video_url = doc.at('//meta[@property="og:video:secure_url"]').attribute('content').value
      @downloader.save_media(:video, video_url, article_url, date)
    else
      image_url = doc.at('//meta[@property="og:image"]').attribute('content').value
      @downloader.save_media(:image, image_url, article_url, date)
    end
  end
end

app/models/scrape/lineblog_crawler.rb
class Scrape::LineblogCrawler
  attr_accessor :errors
  
  def initialize(params)
    member_id = params[:member_id]
    event_id = params[:event_id]
    new_event = params[:event_attributes]
    tag_list = params[:tag_list]
    tmp = params[:tmp]
    @article_url = params[:article_url]
    @article_url.match %r{http://lineblog.me/(.+?)/archives/\d+?\.html} rescue nil
    @lineblogID = params[:lineblogID] || $1
    @host = "http://lineblog.me/#{@lineblogID}/"
    @dir_name = "lineblog/#{@lineblogID}/"
    @downloader = Scrape::Downloader.new(@dir_name, member_id, event_id, new_event, tag_list, tmp)
  end
  
  def validate
    if @lineblogID.nil?
      @errors = '無効なURLです'
      return false
    elsif skip_IDs.include?(@lineblogID)
      @errors = '追跡済みのユーザは指定しないでください'
      return false
    end
    true
  end
  
  def crawl(type: :recent)
    case type
    when :all
      parse_all_articles
    when :recent
      recent_articles.each do |article|
        doc = Nokogiri::HTML.parse(open(article.at_css('link').text))
        parse_article(doc.at_css('article'))
      end
    end
  end
  
  def manually_crawl
    doc = Nokogiri::HTML.parse(open(@article_url)).at_css('article')
    parse_article(doc)
  end
  
  private
  
  # 各ページで、li.paging-next要素の有無で次ページの有無を判定
  def crawl_archives(archive_url)
    doc = Nokogiri::HTML.parse(open(archive_url))
    doc.css('article').each do |article|
      parse_article(article)
    end
    unless doc.css('li.paging-next').empty?
      crawl_archives(doc.css('li.paging-next a').attribute('href').value)
    end
  end
  
  # 全記事の取得はarchives/YYYY-MM.html?p=:numで各記事をさらっていくしかないか。
  def parse_all_articles
    # 2017/05から現在までの全ての月についてeachを回す
    date = Date.new(2017, 5)
    till = Date.today
    while date < till do
      archive_url = "http://lineblog.me/#{@lineblogID}/archives/#{date.year}-#{format('%02d', date.month)}.html"
      crawl_archives(archive_url)
      
      date = date.next_month
    end
  end
  
  # 更新情報はindex.rdfに最新１５件が表示される。
  def recent_articles
    # rdfから取得したitem要素の配列を返す
    doc = Nokogiri::XML.parse(open("http://lineblog.me/#{@lineblogID}/index.rdf"))
    doc.css('item')
  end
  
  # 記事URLのみを集めたような一覧ページがないため、記事URLを指定するようなparseメソッドは賢くない
  # 幸い、各記事はarticle要素でまとめられているため、Nokogiriでパースした要素をこのメソッドに渡すことにする
  # 厄介なことに、instagramに投稿した記事をLINEblogでも記事として表示してくるクソ仕様なので、「ブログ」タグがないものをスキップするようにする
  def parse_article(doc)
    article_url = doc.css('header a').attribute('href').value
    date = Time.parse(doc.css('time').attribute('datetime').value)
    return if date < Date.new(2017, 05, 18)
    doc.css('.article-body-inner img').each do |img|
      path_array = img.attribute('src').value.split('/')
      # instagramからの埋め込み画像の場合はスキップ
      next if path_array[2] == 'scontent.cdninstagram.com'

      extension = '.' + img.attribute('alt').value.split('.')[-1].downcase # ex. image2-13-450x600.JPG => .jpg
      image_url= path_array[0,4].join('/')
      filepath = @dir_name + path_array[3] + extension
      
      @downloader.save_media(:image, image_url, article_url, date, filepath)
    end
  end
  
  def skip_IDs
    Settings.lineblog.regular_crawl.map{|obj| obj.ID}
  end
end

app/models/scrape/youtube_crawler.rb
class Scrape::YoutubeCrawler
  attr_accessor :errors
  
  def initialize(params)
    member_id = params[:member_id]
    event_id = params[:event_id]
    new_event = params[:event_attributes]
    tag_list = params[:tag_list]
    tmp = params[:tmp]
    @uri = Addressable::URI.parse(params[:youtube_url])
    @article_uri = Addressable::URI.parse(params[:article_url]) || @uri
    @downloader = Scrape::Downloader.new('', member_id, event_id, new_event, tag_list, tmp)
  end
  
  def validate
    if !@uri.to_s.match %r{https://www.youtube.com/watch}
      @errors =  '無効なURLです'
      return false
    end
    true
  end
  
  def manually_crawl
    q_hash = Hash[URI.decode_www_form(@uri.query)]
    id = q_hash['v']
    @downloader.save_youtube(id, @uri, @article_uri)
  end
end

app/controllers/scrape_controller.rb
class ScrapeController < ApplicationController
  before_action :approved_user!
  before_action :media_exist?, only: :scrape
  
  def scrape
    media = params[:media]
    class_eval <<-EOM
      def #{media}_crawl
        crawler = Scrape::#{media.classify}Crawler.new(#{media}_params)
        if crawler.validate
          crawler.manually_crawl
          redirect_to scrape_index_path
        else
          redirect_back fallback_location: scrape_index_path, alert: crawler.errors
        end
      end
    EOM
    send "#{media}_crawl"
  end
  
  private
  
  def media_exist?
    medias = %w(lineblog ameblo instagram twitter official_site news_site youtube)
    redirect_back fallback_location: scrape_index_path, alert: '登録されていないパラメータです' unless medias.include?(params[:media])
  end
  
  def lineblog_params
    params.permit(:member_id, :event_id, :tag_list, event_attributes: [:name]).
      merge(params.require(:lineblog).permit(:article_url)).
      merge(tmp: true)
  end
  
  def ameblo_params
    params.permit(:member_id, :event_id, :tag_list, event_attributes: [:name]).
      merge(params.require(:ameblo).permit(:article_url)).
      merge(tmp: true)
  end
  
  def instagram_params
    params.permit(:member_id, :event_id, :tag_list, event_attributes: [:name]).
      merge(params.require(:instagram).permit(:article_url)).
      merge(tmp: true)
  end
  
  def twitter_params
    params.permit(:member_id, :event_id, :tag_list, event_attributes: [:name]).
      merge(params.require(:twitter).permit(:type, :screen_name, :since, :until, :number, :tweet_url)).
      merge(tmp: true, user_type: :admin)
  end
  
  def official_site_params
    params.permit(:member_id, :event_id, :tag_list, event_attributes: [:name]).
      merge(params.require(:official_site).permit(:page_url, :allowed_links, :depth_limit)).
      merge(tmp: true)
  end
  
  def news_site_params
    params.permit(:member_id, :event_id, :tag_list, event_attributes: [:name]).
      merge(params.require(:news_site).permit(:article_url)).
      merge(tmp: true)
  end
  
  def youtube_params
    params.permit(:member_id, :event_id, :tag_list, event_attributes: [:name]).
      merge(params.require(:youtube).permit(:youtube_url, :article_url)).
      merge(tmp: true)
  end
end

app/helpers/scrape_helper.rb
module ScrapeHelper
end

app/views/scrape/_footer.html.haml
%footer
  %nav.navbar.navbar-default.navbar-fixed-bottom{:role => "navigation"}
    .container-fluid
      %ul.nav.navbar-nav.navbar-right
        %li= link_to '戻る', scrape_index_path

app/views/scrape/_form.html.haml
- if action_name == 'lineblog'
  .center-block
    = url_field_tag 'lineblog[article_url]', nil, placeholder: 'LINEブログの記事URLを入力してください', required: true

- if action_name == 'ameblo'
  .center-block
    = url_field_tag 'ameblo[article_url]', nil, placeholder: 'アメブロの記事URLを入力してください', required: true

- if action_name == 'instagram'
  .center-block
    = text_field_tag 'instagram[article_url]', nil, placeholder: 'ポストURLを入力してください', required: true

- if action_name == 'twitter'
  .center-block
    = select_tag 'twitter[type]', options_for_select([ ['期間を指定して取得(約10日前まで)', 'date'], ['ツイート数を指定して取得(3,200まで)', 'number'], ['ツイートURLを直接指定して取得', 'tweet'] ]), include_blank: true, required: true
  .center-block.switch.date.number
    = text_field_tag 'twitter[screen_name]', nil, placeholder: 'TwitterID'
  .center-block.switch.date
    %span since:
    = date_field_tag 'twitter[since]', Date.today, max: Date.today
  .center-block.switch.date
    %span until:
    = date_field_tag 'twitter[until]', Date.today, max: Date.today
  .center-block.switch.number
    %span ツイート数：
    = number_field_tag 'twitter[number]', nil, min: 1, max: 3200
  .center-block.switch.tweet
    = url_field_tag 'twitter[tweet_url]', nil, placeholder: 'https://twitter.com/<user_id>/status/<tweet_id>'

- if action_name == 'official_site'
  .center-block
    = url_field_tag 'official_site[page_url]', nil, placeholder: '取得するページのURLを指定してください', required: true
  .center-block
    = url_field_tag 'official_site[allowed_links][]', nil, placeholder: 'もし異なるドメインに飛んでから画像をとるなら指定してください（通常は不要）'
  .center-block
    %p ページ内のみ：0、1つ先のリンクまで：1
    = number_field_tag 'official_site[depth_limit]', nil, min:0, max:1, required: true

- if action_name == 'news_site'
  .center-block
    = url_field_tag 'news_site[article_url]', nil, placeholder: '記事URLを指定してください', required: true

- if action_name == 'youtube'
  .center-block
    = url_field_tag 'youtube[youtube_url]', nil, placeholder: '< https://www.youtube.com/watch?v=... >', required: true
  .center-block
    = url_field_tag 'youtube[article_url]', nil, placeholder: '本記事のURLがあれば指定してください'

.center-block.member-form
  %span メンバー：
  = select_tag :member_id, options_from_collection_for_select(Member.all, :id, :name), include_blank: true, required: true
.center-block.event-form
  %span イベント：
  = select_tag :event_id, options_from_collection_for_select(Event.all, :id, :name), include_blank: true
  %button.btn.new-record{type: 'button'} イベント新規作成
.center-block.tags-form
  %span タグ：
  = text_field_tag :tag_list, nil, {'data-role': 'tagsinput', placeholder: 'tag separated with , or Enter', class: 'tag-list'}
.center-block
  = submit_tag '追加', class: 'btn btn-default'

app/views/scrape/ameblo.html.haml
.detail
  = form_tag scrape_path(media: 'ameblo'), name: 'ameblo' do
    = render 'form'
= render 'footer'

app/views/scrape/index.html.haml
.heading
  = button_to 'lineblog', scrape_lineblog_path, method: :get, class: 'btn btn-default'
  = button_to 'ameblo', scrape_ameblo_path, method: :get, class: "btn btn-default"
  = button_to 'instagram', scrape_instagram_path, method: :get, class: "btn btn-default"
  = button_to 'twitter', scrape_twitter_path, method: :get, class: "btn btn-default"
  = button_to 'official site', scrape_official_site_path, method: :get, class: "btn btn-default"
  = button_to 'news site', scrape_news_site_path, method: :get, class: "btn btn-default"
  = button_to 'youtube', scrape_youtube_path, method: :get, class: "btn btn-default"

app/views/scrape/instagram.html.haml
.detail
  = form_tag scrape_path(media: 'instagram'), name: 'instagram' do
    = render 'form'
= render 'footer'

app/views/scrape/lineblog.html.haml
.detail
  = form_tag scrape_path(media: 'lineblog'), name: 'lineblog' do
    = render 'form'
= render 'footer'

app/views/scrape/news_site.html.haml
.detail
  = form_tag scrape_path(media: 'news_site'), name: 'news_site' do
    =render 'form'
= render 'footer'

app/views/scrape/official_site.html.haml
.detail
  = form_tag scrape_path(media: 'official_site'), name: 'official_site' do
    =render 'form'
= render 'footer'

app/views/scrape/twitter.html.haml
.detail
  = form_tag scrape_path(media: 'twitter'), name: 'twitter' do
    = render 'form'
= render 'footer'

app/views/scrape/youtube.html.haml
.detail
  = form_tag scrape_path(media: 'youtube'), name: 'youtube' do
    = render 'form'
= render 'footer'