config/routes.rb
Rails.application.routes.draw do
  root 'top_page#index'
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }, skip: :sessions
  devise_scope :user do
    delete 'users/logout', to: 'users/sessions#destroy'
    delete 'users/destroy', to: 'users/registrations#destroy'
    get 'users/index', to: 'users/admin#index'
    patch 'users/approve', to: 'users/admin#approve'
    patch 'users/admin', to: 'users/admin#admin'
  end

  post :scrape, to: 'scrape#scrape'
  namespace :scrape do
    get :index
    get :lineblog
    get :ameblo
    get :instagram
    get :twitter
    get :official_site
    get :news_site
    get :youtube
  end

  resources :media_contents, constraints: { id: /\d+/ }, only: [ :index, :edit, :show, :update ] do
    collection do
      get :tmp
      patch :tmp, to: 'media_contents#multiple'
      get :deletion_request
      patch :deletion_request, to: 'media_contents#hide'
      get :search
    end
  end
  get :pictures, to: 'media_contents#pictures'
  get :videos, to: 'media_contents#videos'
  
  get 'tweets' => 'tweet#index'
end

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default.navbar-fixed-top{:role => "navigation"}
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      = link_to 'YuiKaori', root_path, class: 'navbar-brand'
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      - if user_signed_in?
        / 左側のコンポーネント
        %ul.nav.navbar-nav
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "./", :role => "button"}
              MENU
              %span.caret
            %ul.dropdown-menu
              %li= link_to 'ゆいかおり', search_media_contents_path(column: 'member', media_content: {member: 1})
              %li= link_to '小倉唯', search_media_contents_path(column: 'member', media_content: {member: 2})
              %li= link_to '石原夏織', search_media_contents_path(column: 'member', media_content: {member: 3})
              %li.divider{:role => "separator"}
              / 検索フォーム
              %li
                = form_tag search_media_contents_path, method: :get, class: 'navbar-form navbar-left', role: 'search' do
                  .form-group
                    = hidden_field_tag :column, 'date'
                    %p since:
                    = date_field_tag 'media_content[since]', Date.today, class: 'form-control', max: Date.today
                    %p until:
                    = date_field_tag 'media_content[until]', Date.today, class: 'form-control', max: Date.today
                  = submit_tag '検索', class: 'btn btn-default'
              %li.divider{:role => "separator"}
              %li
                = form_tag search_media_contents_path, method: :get, class: 'navbar-form navbar-left', role: 'search' do
                  .form-group
                    = hidden_field_tag :column, 'event'
                    = text_field_tag('media_content[event]', nil, class: 'form-control', placeholder: 'イベント検索')
                  = submit_tag '検索', class: 'btn btn-default'
              %li.divider{:role => "separator"}
              %li
                = form_tag search_media_contents_path, method: :get, class: 'navbar-form navbar-left', role: 'search' do
                  .form-group
                    = hidden_field_tag :column, 'tag'
                    = text_field_tag('media_content[tag]', nil, class: 'form-control', placeholder: 'タグ検索')
                  = submit_tag '検索', class: 'btn btn-default'
              %li
                = form_tag search_media_contents_path, method: :get, class: 'navbar-form navbar-left', role: 'search' do
                  .form-group
                    = hidden_field_tag :column, 'media'
                    = text_field_tag 'media_content[media]', nil, class: 'form-control', placeholder: 'メディア名検索'
                  = submit_tag '検索', class: 'btn btn-default'
          %li= link_to '一覧表示', media_contents_path
          %li= link_to '画像のみ', pictures_path
          %li= link_to '動画のみ', videos_path
          - if current_user.admin?
            %li= link_to '削除／表示許可', tmp_media_contents_path
        / 右側のコンポーネント
        %ul.nav.navbar-nav.navbar-right
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :role => "button"}
              = current_user.username
            %ul.dropdown-menu
              %li= image_tag current_user.image, class: 'img-circle'
              %li= current_user.username
              %li @#{current_user.screen_name}
              %li 承認：#{current_user.approved}
              %li 管理者：#{current_user.admin}
              %li.divider{:role => "separator"}
              %li= link_to 'ログアウト', users_logout_path, method: :delete
              %li= link_to 'アカウント削除', users_destroy_path, method: :delete

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= full_title(yield(:title))
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    - if File.exist? "#{Rails.root}/app/assets/stylesheets/#{controller.controller_name}.scss"
      = stylesheet_link_tag    controller.controller_name, media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    - if File.exist? "#{Rails.root}/app/assets/javascripts/#{controller.controller_name}.coffee"
      = javascript_include_tag controller.controller_name, 'data-turbolinks-track': 'reload'
  %body
    %header
      = render 'layouts/header'
    %section
      = yield
    #notice
      - if flash[:notice]
        = javascript_tag "alert('#{flash.now[:notice]}')"
    #alert
      - if flash[:alert]
        = javascript_tag "alert('#{flash.now[:alert]}')"